Repository Yoyakso/COMKET_FE, pull requests merged in 2025-04, with the labels that each got.

#3 svgr 관련 에러 처리 및 Button, Badge 컴포넌트 생성
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/.gitkeep
  src/components/common/badge/Badge.Style.ts
  src/components/common/badge/Badge.tsx
  src/components/common/button/Button.Style.ts
  src/components/common/button/Button.tsx
  src/styles/globalStyle.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/types/svg.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ✨ feature, 🐣 yumin

#4 Dropdown & Search 컴포넌트 추가
  src/assets/icons/ChevronDown.svg
  src/assets/icons/ChevronUp.svg
  src/assets/icons/DropdownIcon.svg
  src/assets/icons/SearchClearIcon.svg
  src/assets/icons/SearchIcon.svg
  src/components/common/dropdown/Dropdown.style.ts
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/search/Search.style.ts
  src/components/common/search/Search.tsx
  src/pages/loginPage/LoginPage.tsx
  src/styles/color.ts
Labels: 💄 ui, 😺 wantyeon

#5 Chip, LoginButton, NavProfile 컴포넌트 생성
  src/assets/icons/CloseIcon.svg
  src/assets/icons/GoogleIcon.svg
  src/assets/icons/InformationIcon.svg
  src/assets/icons/KeyIcon.svg
  src/assets/icons/ListIcon.svg
  src/assets/icons/MemberIcon.svg
  src/assets/icons/PlanIcon.svg
  src/assets/icons/PlusIcon.svg
  src/assets/icons/ProfileIcon.svg
  src/assets/icons/ProfileImageIcon.svg
  src/assets/icons/SettingIcon.svg
  src/assets/icons/UploadIcon.svg
  src/components/common/button/Button.tsx
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/Chip.tsx
  src/components/common/footer/Footer.Style.ts
  src/components/common/footer/Footer.tsx
  src/components/common/navBar/NavProfile.Style.ts
  src/components/common/navBar/NavProfile.tsx
  src/components/login/LoginButton.Style.ts
  src/components/login/LoginButton.tsx
  src/styles/color.ts
Labels: ✨ feature, 💄 ui, 🐣 yumin

#6 GNB, LNB 컴포넌트 생성
  public/fonts/Lexend-ExtraBold.woff
  src/assets/icons/COMKET.svg
  src/assets/icons/InfoIcon.svg
  src/assets/icons/QuestionIcon.svg
  src/assets/icons/index.ts
  src/components/common/navBar/GlobalNavBar.Style.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/components/common/navBar/LocalNavBar.Style.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/common/navBar/WorkspaceSelector.Style.ts
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/common/search/Search.style.ts
  src/components/common/search/Search.tsx
  src/styles/globalStyle.ts
Labels: ✨ feature, 💄 ui, 🐣 yumin
