Repository Yoyakso/COMKET_FE, pull requests merged in 2025-06, with the labels that each got.

#111 feat: 눈높이 요약 api 연동 및 리팩토링
  src/api/Ai.ts
  src/components/thread/threadAiSummary/ThreadAiSummary.Style.ts
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/AssignCell.tsx
  src/components/ticket/TicketRow.Style.ts
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketView/TicketListView.tsx
  src/constants/ticketTemplateData.ts
  src/pages/threadPage/ThreadPage.Style.ts
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/types/eyeLevel.ts
Labels: ⚙️ api, ✨ feature, 🛠 refactor, 🐣 yumin

#112 feat: 액션 아이템 클릭 시 하위 티켓 생성
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketModal/TicketTemplateModal.tsx
  src/constants/ticketTemplateData.ts
  src/pages/threadPage/ThreadPage.Style.ts
  src/pages/threadPage/ThreadPage.tsx
Labels: ✨ feature, 🐣 yumin

#114 ref: 스레드 정보란에 하위 티켓 정보 렌더링
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/pages/threadPage/ThreadPage.tsx
Labels: 🛠 refactor, 🐣 yumin

#123 feat: 알림이 있는 티켓의 경우 알림 표시 띄우기
  src/components/ticket/AssignCell.tsx
  src/components/ticket/TicketRow.Style.ts
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketView/TicketListView.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 yumin

#132 fix: Notification 호출로 인한 초기 렌더링 에러 방지 & 권한 배너 구현
  public/firebase-messaging-sw.js
  src.zip
  src/App.tsx
  src/AppInitializer.tsx
  src/components/common/banner/NotificationPermissionBanner.Style.ts
  src/components/common/banner/NotificationPermissionBanner.tsx
  src/hooks/useFcm.ts
  src/utils/firebase.ts
Labels: 🐞 bug, ✨ feature, 😺 wantyeon

#137 feat: 칸반보드 OTHERS 칼럼 드래그앤드롭 상태 선택 모달 추가
  src/components/login/LoginForm.tsx
  src/components/login/OauthLoginButton.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketModal/StatusSelectModal.Style.ts
  src/components/ticketModal/StatusSelectModal.tsx
  src/components/ticketView/TicketBoardView.tsx
Labels: ✨ feature, 🐣 yumin

#139 feat: 토큰 만료 처리 및 axiosInstance 적용 / 로컬 HTTPS 환경 구성
  package-lock.json
  package.json
  src/api/Ai.ts
  src/api/Alarm.ts
  src/api/Member.ts
  src/api/Oauth.ts
  src/api/Project.ts
  src/api/Ticket.ts
  src/api/Workspace.ts
  src/api/axiosInstance.ts
  src/components/login/SignUpForm.tsx
  src/pages/accountInfoPage/AccountInfoPage.tsx
  src/pages/profilePage/profilePage.tsx
  vite.config.ts
Labels: 🧹 chore, ✨ feature, 🛠 refactor, 🐣 yumin

#144 ref: 티켓 담당자 다중 할당 및 패널 정보 확장, 타입 에러 수정
  public/images/demo-1.png
  public/images/demo-2.png
  public/images/demo-3.png
  public/images/demo-4.png
  public/images/dummy-1.png
  src/api/Ticket.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/memberDetailPanel/MemberDetailPanel.tsx
  src/components/project/AddProjectMemberModal.tsx
  src/components/project/ProjectMemberModal.tsx
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/AssignCell.tsx
  src/components/ticket/PriorityDropdown.tsx
  src/components/ticket/StatusDropdown.tsx
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.Style.ts
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketModal/TicketTemplateModal.tsx
  src/components/ticketView/TicketCard.tsx
  src/components/ticketView/TicketListView.tsx
  src/pages/mainPage/MainPage.Style.ts
  src/pages/mainPage/MainPage.tsx
  src/pages/myTicketPage/MyTicketPage.tsx
  src/pages/profilePage/profilePage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/types/ticket.ts
  src/utils/ticketMapper.ts
  src/utils/ticketTemplateMapper.ts
Labels: 🧹 chore, 🛠 refactor, 🐣 yumin

#148 feat: Billing 페이지 구축 및 비밀번호 재설정, 알림/FCM 기능 개선
  package-lock.json
  package.json
  src/Router.tsx
  src/api/Alarm.ts
  src/api/Billing.ts
  src/api/Oauth.ts
  src/api/notification.ts
  src/components/billing/BillingChartSection.Style.ts
  src/components/billing/BillingChartSection.tsx
  src/components/billing/BillingPlanSection.Style.ts
  src/components/billing/BillingPlanSection.tsx
  src/components/billing/PaymentCompleteModal.Style.ts
  src/components/billing/PaymentCompleteModal.tsx
  src/components/billing/PaymentModal.Style.ts
  src/components/billing/PaymentModal.tsx
  src/components/billing/PlanSelectModal.Style.ts
  src/components/billing/PlanSelectModal.tsx
  src/components/billing/UpgradePlanModal.Style.ts
  src/components/billing/UpgradePlanModal.tsx
  src/components/common/auth/RequireAuth.tsx
  src/components/common/banner/NotificationPermissionBanner.tsx
  src/components/common/navBar/GlobalNavBar.tsx
  src/components/common/navBar/LocalNavBar.Style.ts
  src/components/common/navBar/ProjectNavBar.tsx
  src/components/common/navBar/SettingNavBar.tsx
  src/components/login/LoginForm.tsx
  src/components/member/MemberHeader.tsx
  src/components/member/MemberTable.tsx
  src/components/password/FindPassword.tsx
  src/components/password/FindPasswordComplete.tsx
  src/components/password/ResetPassword.Style.ts
  src/components/password/ResetPassword.tsx
  src/components/ticket/TicketTable.tsx
  src/components/workspace/WorkspaceSelectorDropdown.tsx
  src/constants/planData.ts
  src/hooks/useBillingInfo.ts
  src/hooks/useFcm.ts
  src/pages/billingPage/BillingPage.Style.ts
  src/pages/billingPage/BillingPage.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/planPage/PlanPage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
  src/types/billing.ts
  src/utils/mapPlanId.ts
  src/utils/parseMonthlyDataByYear.ts
Labels: 🐞 bug, ⚙️ api, ✨ feature, 💄 ui, 😺 wantyeon

#150 feat: reply시 해당 부모 댓글로 이동 및 하이라이트 처리
  src/api/Thread.ts
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/hooks/useWebSocket.ts
  src/pages/profilePage/profilePage.tsx
  src/pages/threadPage/ThreadPage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
  src/stores/chatStore.ts
  src/stores/userStore.ts
  src/types/message.ts
Labels: ✨ feature, 💄 ui, 🐣 yumin

#155 feat: 스레드 파일 업로드 api 연동 및 파일 미리보기 기능 추가
  package-lock.json
  package.json
  src/api/Alarm.ts
  src/api/Thread.ts
  src/api/Workspace.ts
  src/components/login/LoginForm.tsx
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticketModal/CreateTicketModal.tsx
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/threadPage/ThreadPage.tsx
  src/types/message.ts
Labels: 🐞 bug, ✨ feature, 🐣 yumin

#164 fix: 메세지 수정 시 멘션 안 되는 문제 해결
  src/api/Thread.ts
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/hooks/useFcm.ts
  src/pages/threadPage/ThreadPage.tsx
  src/sw.js
Labels: 🐞 bug, 🛠 refactor, 🐣 yumin

#171 feat: 공통 UI 컴포넌트 테스트
  package-lock.json
  package.json
  src/components/common/badge/Badge.test.tsx
  src/components/common/badge/Badge.tsx
  src/components/common/button/Button.test.tsx
  src/components/common/button/Button.tsx
  src/components/common/chip/Chip.test.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/dropdown/Dropdown.test.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/markdownEditor/MarkdowEditor.test.tsx
  src/components/common/modal/DeleteModal.test.tsx
  src/components/common/modal/DeleteModal.tsx
  src/components/common/radio/Radio.test.tsx
  src/components/common/search/Search.test.tsx
  src/components/common/textInput/TextInput.test.tsx
  src/components/common/toggle/Toggle.test.tsx
  src/pages/mainPage/MainPage.tsx
  vite.config.ts
Labels: 🧪 test, ✨ feature
