Repository Yoyakso/COMKET_FE, pull requests merged in 2025-05, with the labels that each got.

#8 Text Input, CheckBox, Radio, Toggle 컴포넌트 생성
  src.zip
  src/assets/icons/CheckIcon.svg
  src/assets/icons/ClearIcon.svg
  src/assets/icons/CloseIcon2.svg
  src/assets/icons/EyeOffIcon.svg
  src/assets/icons/EyeOnIcon.svg
  src/assets/icons/MinusIcon.svg
  src/assets/icons/PasswordDotIcon.svg
  src/components/common/checkbox/CheckBox.style.ts
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/radio/Radio.style.ts
  src/components/common/radio/Radio.tsx
  src/components/common/search/Search.tsx
  src/components/common/textInput/TextInput.style.ts
  src/components/common/textInput/TextInput.tsx
  src/components/common/toggle/Toggle.style.ts
  src/components/common/toggle/Toggle.tsx
  src/pages/loginPage/LoginPage.tsx
Labels: ✨ feature, 💄 ui, 😺 wantyeon

#10 공통 UI 컴포넌트 생성
  public/fonts/Lexend-ExtraBold.woff
  src.zip
  src/assets/icons/COMKET.svg
  src/assets/icons/CheckIcon.svg
  src/assets/icons/ChevronDown.svg
  src/assets/icons/ChevronUp.svg
  src/assets/icons/ClearIcon.svg
  src/assets/icons/CloseIcon.svg
  src/assets/icons/CloseIcon2.svg
  src/assets/icons/DropdownIcon.svg
  src/assets/icons/EyeOffIcon.svg
  src/assets/icons/EyeOnIcon.svg
  src/assets/icons/GoogleIcon.svg
  src/assets/icons/InfoIcon.svg
  src/assets/icons/InformationIcon.svg
  src/assets/icons/KeyIcon.svg
  src/assets/icons/ListIcon.svg
  src/assets/icons/MemberIcon.svg
  src/assets/icons/MinusIcon.svg
  src/assets/icons/PasswordDotIcon.svg
  src/assets/icons/PlanIcon.svg
  src/assets/icons/PlusIcon.svg
  src/assets/icons/ProfileIcon.svg
  src/assets/icons/ProfileImageIcon.svg
  src/assets/icons/QuestionIcon.svg
  src/assets/icons/SearchIcon.svg
  src/assets/icons/SettingIcon.svg
  src/assets/icons/UploadIcon.svg
  src/assets/icons/index.ts
  src/components/common/button/Button.tsx
  src/components/common/checkbox/CheckBox.style.ts
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/Chip.tsx
  src/components/common/dropdown/Dropdown.style.ts
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/footer/Footer.Style.ts
  src/components/common/footer/Footer.tsx
  src/components/common/navBar/GlobalNavBar.Style.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/components/common/navBar/LocalNavBar.Style.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/common/navBar/NavProfile.Style.ts
  src/components/common/navBar/NavProfile.tsx
  src/components/common/navBar/WorkspaceSelector.Style.ts
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/common/radio/Radio.style.ts
  src/components/common/radio/Radio.tsx
  src/components/common/search/Search.style.ts
  src/components/common/search/Search.tsx
  src/components/common/textInput/TextInput.style.ts
  src/components/common/textInput/TextInput.tsx
  src/components/common/toggle/Toggle.style.ts
  src/components/common/toggle/Toggle.tsx
  src/components/login/LoginButton.Style.ts
  src/components/login/LoginButton.tsx
  src/pages/loginPage/LoginPage.tsx
  src/styles/color.ts
  src/styles/globalStyle.ts
Labels: ✨ feature, 💄 ui

#15 로그인 로직 구현
  .env.development
  .env.production
  src/Router.tsx
  src/api/.gitkeep
  src/api/Oauth.ts
  src/assets/icons/FilterIcon.svg
  src/assets/icons/index.ts
  src/components/login/OauthLoginButton.tsx
  src/components/member/MemberHeader.Style.ts
  src/components/member/MemberHeader.tsx
  src/pages/loginPage/GoogleRedirect.Style.ts
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/memberPage/MemberPage.Style.ts
  src/pages/memberPage/MemberPage.tsx
  src/types/member.ts
Labels: ✨ feature, 🐣 yumin

#19 프로젝트, 멤버 관리 UI 구현
  src/Router.tsx
  src/assets/icons/DotIcon.svg
  src/assets/icons/index.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/member/MemberHeader.tsx
  src/components/member/MemberRow.Style.ts
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.Style.ts
  src/components/member/MemberTable.tsx
  src/components/project/ProjectHeader.Style.ts
  src/components/project/ProjectHeader.tsx
  src/components/project/ProjectRow.Style.ts
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.Style.ts
  src/components/project/ProjectTable.tsx
  src/components/workspace/InviteModal.Style.ts
  src/components/workspace/InviteModal.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/projectPage/ProjectPage.Style.ts
  src/pages/projectPage/ProjectPage.tsx
  src/types/project.ts
Labels: ✨ feature, 💄 ui, 🐣 yumin

#26 Feat/4 4 3/project member UI
  package-lock.json
  package.json
  src/api/Oauth.ts
  src/components/login/SignUpForm.tsx
  src/components/member/MemberHeader.Style.ts
  src/components/member/MemberHeader.tsx
  src/components/member/MemberRow.tsx
  src/components/member/RemoveMemberModal.Style.ts
  src/components/member/RemoveMemberModal.tsx
  src/components/project/CreateProjectModal.Style.tsx
  src/components/project/CreateProjectModal.tsx
  src/components/project/EmptyProject.Style.ts
  src/components/project/EmptyProject.tsx
  src/components/project/ProjectHeader.Style.ts
  src/components/project/ProjectHeader.tsx
  src/main.tsx
  src/pages/projectPage/ProjectPage.Style.ts
  src/pages/projectPage/ProjectPage.tsx
Labels: ✨ feature, 🐣 yumin

#27 회원가입 관련 로직 구현 및 ui 수정
  src/api/Oauth.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/components/login/SignUpComplete.tsx
  src/components/login/SignUpForm.Style.ts
  src/components/login/SignUpForm.tsx
  src/components/member/MemberTable.Style.ts
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.Style.ts
  src/main.tsx
  src/pages/loginPage/GoogleRedirect.tsx
Labels: ✨ feature, 🐣 yumin

#28 회원가입 api 연동 및 ui 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/api/CreateWorkspace.ts
  src/api/DeleteWorkspace.ts
  src/api/InviteCode.ts
  src/api/Oauth.ts
  src/api/Workspace.ts
  src/api/WorkspaceImage.ts
  src/api/WorkspaceInfo.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/components/common/textInput/TextInput.style.ts
  src/components/common/textInput/TextInput.tsx
  src/components/login/SignUpComplete.tsx
  src/components/login/SignUpForm.Style.ts
  src/components/login/SignUpForm.tsx
  src/components/member/MemberHeader.Style.ts
  src/components/member/MemberHeader.tsx
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.Style.ts
  src/components/member/RemoveMemberModal.Style.ts
  src/components/member/RemoveMemberModal.tsx
  src/components/project/CreateProjectModal.Style.tsx
  src/components/project/CreateProjectModal.tsx
  src/components/project/EmptyProject.Style.ts
  src/components/project/EmptyProject.tsx
  src/components/project/ProjectHeader.Style.ts
  src/components/project/ProjectHeader.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.Style.ts
  src/components/workspace/ImageUpload.Style.ts
  src/components/workspace/ImageUpload.tsx
  src/components/workspace/WorkspaceDelete.Style.ts
  src/components/workspace/WorkspaceDelete.tsx
  src/components/workspace/WorkspaceExit.Style.ts
  src/components/workspace/WorkspaceExit.tsx
  src/main.tsx
  src/pages/InviteCodePage/InviteCodePage.tsx
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/projectPage/ProjectPage.Style.ts
  src/pages/projectPage/ProjectPage.tsx
  src/pages/workspaceCreatePage/workspaceCreatePage.Style.ts
  src/pages/workspaceCreatePage/workspaceCreatePage.tsx
  src/pages/workspaceManagePage/WorkspaceInfoPage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
Labels: ⚙️ api, ✨ feature

#31 프로젝트 관련 컴포넌트 수정
  src/components/project/AddProjectMemberModal.Style.ts
  src/components/project/AddProjectMemberModal.tsx
  src/components/project/CreateProjectModal.tsx
  src/components/project/EmptyProject.tsx
  src/components/project/ProjectMemberModal.Style.ts
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectModal.Style.ts
  src/components/project/ProjectModal.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.tsx
  src/components/project/ViewProjectModal.tsx
  src/pages/projectPage/ProjectPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 yumin

#36 프로젝트 목록 조회 및 인증코드 검증 api 연동
  src/api/Member.ts
  src/api/Oauth.ts
  src/api/Project.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/login/SignUpForm.Style.ts
  src/components/login/SignUpForm.tsx
  src/components/project/ProjectRow.Style.ts
  src/components/project/ProjectRow.tsx
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/types/project.ts
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#37 프로젝트 목록 조회 및 인증코드 검증 api 연동
  src/api/Member.ts
  src/api/Oauth.ts
  src/api/Project.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/login/SignUpForm.Style.ts
  src/components/login/SignUpForm.tsx
  src/components/project/ProjectRow.Style.ts
  src/components/project/ProjectRow.tsx
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/types/project.ts
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#42 프로필 설정 및 계정 정보 조회 페이지 생성
  src/Router.tsx
  src/assets/icons/index.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/member/MemberHeader.tsx
  src/components/project/ProjectHeader.tsx
  src/constants/profileOptions.ts
  src/pages/ProfilePage/profilePage.Style.ts
  src/pages/ProfilePage/profilePage.tsx
  src/pages/accountInfoPage/AccountInfoPage.Style.ts
  src/pages/accountInfoPage/AccountInfoPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 yumin

#47 멤버 및 프로젝트 관련 api 연동
  package-lock.json
  package.json
  src/api/Member.ts
  src/api/Project.ts
  src/components/member/MemberHeader.tsx
  src/components/member/MemberRow.Style.ts
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.tsx
  src/components/project/ProjectHeader.tsx
  src/components/project/ProjectModal.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/RemoveProjectModal.Style.ts
  src/components/project/RemoveProjectModal.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/projectPage/ProjectPage.Style.ts
  src/pages/projectPage/ProjectPage.tsx
  src/types/member.ts
  src/types/project.ts
  src/utils/avatarColor.ts
  src/utils/dateFormat.ts
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#48 멤버 및 프로젝트 관련 api 연동
  package-lock.json
  package.json
  src/api/Member.ts
  src/api/Project.ts
  src/components/member/MemberHeader.tsx
  src/components/member/MemberRow.Style.ts
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.tsx
  src/components/project/ProjectHeader.tsx
  src/components/project/ProjectModal.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/RemoveProjectModal.Style.ts
  src/components/project/RemoveProjectModal.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/projectPage/ProjectPage.Style.ts
  src/pages/projectPage/ProjectPage.tsx
  src/types/member.ts
  src/types/project.ts
  src/utils/avatarColor.ts
  src/utils/dateFormat.ts
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#54 프로젝트 멤버 관련 api 연동
  src/Router.tsx
  src/api/Oauth.ts
  src/api/Project.ts
  src/components/login/LoginForm.tsx
  src/components/login/SignUpForm.tsx
  src/components/project/AddProjectMemberModal.tsx
  src/components/project/ProjectMemberModal.Style.ts
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectRow.Style.ts
  src/components/project/ProjectTable.Style.ts
  src/pages/projectPage/ProjectPage.tsx
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#56 프로젝트 멤버 및 직접 로그인 api 연동
  src/Router.tsx
  src/api/Oauth.ts
  src/api/Project.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/login/LoginForm.tsx
  src/components/login/SignUpForm.tsx
  src/components/project/AddProjectMemberModal.tsx
  src/components/project/ProjectMemberModal.Style.ts
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectRow.Style.ts
  src/components/project/ProjectTable.Style.ts
  src/pages/InviteCodePage/InviteCodePage.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/pages/workspaceCreatePage/CreateWorkspaceForm.tsx
  src/pages/workspaceCreatePage/workspaceCreatePage.Style.ts
  src/pages/workspaceCreatePage/workspaceCreatePage.tsx
  src/pages/workspaceManagePage/WorkspaceInfoPage.tsx
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#57 feat: 프로젝트 admin 객체 데이터 적용
  package-lock.json
  package.json
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectModal.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/types/project.ts
Labels: ✨ feature, 🐣 yumin

#58 feat: 프로젝트 admin 객체 데이터 적용
  package-lock.json
  package.json
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectModal.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/types/project.ts
Labels: ✨ feature, 🐣 yumin

#61 zustand 기반 유저 정보 및 워크스페이스 정보 전역 상태 관리
  index.html
  public/favicon.svg
  src/api/Member.ts
  src/api/Project.ts
  src/api/Workspace.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/login/LoginForm.tsx
  src/components/member/MemberRow.Style.ts
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.tsx
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectRow.tsx
  src/components/project/ProjectTable.tsx
  src/components/workspace/InviteModal.tsx
  src/pages/accountInfoPage/AccountInfoPage.tsx
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/pages/workspaceCreatePage/workspaceCreatePage.tsx
  src/pages/workspaceManagePage/WorkspaceInfoPage.Style.ts
  src/pages/workspaceManagePage/WorkspaceInfoPage.tsx
  src/stores/userStore.ts
  src/stores/workspaceStore.ts
  src/utils/.gitkeep
Labels: ✨ feature, 🛠 refactor, 🐣 yumin

#63 Refactor/global state and ux
  src/App.tsx
  src/AppInitializer.tsx
  src/components/common/modal/DeleteModal.Style.ts
  src/components/common/modal/DeleteModal.tsx
  src/components/common/navBar/LocalNavBar.tsx
  src/components/common/navBar/NavProfile.Style.ts
  src/components/common/navBar/NavProfile.tsx
  src/components/member/MemberRow.tsx
  src/components/member/RemoveMemberModal.tsx
  src/components/member/RemoveWorkspaceMemberModal.tsx
  src/components/project/AddProjectMemberModal.Style.ts
  src/components/project/AddProjectMemberModal.tsx
  src/components/project/ProjectMemberModal.tsx
  src/components/project/ProjectModal.tsx
  src/components/project/ProjectRow.Style.ts
  src/components/project/ProjectRow.tsx
  src/components/project/RemoveProjectMemberModal.tsx
  src/components/project/RemoveProjectModal.Style.ts
  src/components/project/RemoveProjectModal.tsx
  src/pages/memberPage/MemberPage.tsx
  src/pages/profilePage/profilePage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
  src/stores/userStore.ts
Labels: ✨ feature, 🛠 refactor, 🐣 yumin

#71 feat: 티켓 생성 모달 구현
  package-lock.json
  package.json
  src/components/common/markdownEditor/MarkdownEditor.Style.ts
  src/components/common/markdownEditor/MarkdownEditor.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 yumin

#72 feat: 티켓 생성 및 조회 API 연동
  src/Router.tsx
  src/api/Project.ts
  src/api/Ticket.ts
  src/components/project/ProjectRow.tsx
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.Style.ts
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketView/TicketBoardView.tsx
  src/components/ticketView/TicketListView.Style.ts
  src/components/ticketView/TicketListView.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.Style.ts
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/types/project.ts
  src/types/ticket.ts
Labels: ⚙️ api, ✨ feature, 🐣 yumin

#74 feat: WebSocket 연결 hook 및 관련 컴포넌트 생성
  src/Router.tsx
  src/api/Ticket.ts
  src/components/common/dropdown/Filter.tsx
  src/components/thread/threadAiSummary/ThreadAiSummary.Style.ts
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/PriorityDropdown.tsx
  src/components/ticket/StatusDropdown.tsx
  src/components/ticket/TicketToolbar.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketView/TicketListView.tsx
  src/constants/ticketData.ts
  src/hooks/useWebSocket.ts
  src/pages/threadPage/ThreadPage.Style.ts
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/stores/chatStore.ts
  src/stores/ticketStore.ts
Labels: ✨ feature, 💄 ui, 🐣 yumin

#75 WebSocket handshake 실패 원인 디버깅 및 환경 변수 추가
  .env.development
  .env.production
  .gitignore
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/ticketModal/CreateTicketModal.tsx
  src/hooks/useWebSocket.ts
Labels: 🐞 bug, 🐣 yumin

#77 Feat/2 1 4/web socket
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/markdownEditor/MarkdownEditor.tsx
  src/components/thread/threadChat/ThreadChat.tsx
  src/hooks/useWebSocket.ts
  src/pages/threadPage/ThreadPage.tsx
Labels: 🐞 bug, 🐣 yumin

#79 WebSocket 연결 및 스레드 공간 스타일링
  package-lock.json
  package.json
  src/components/common/markdownEditor/MarkdownEditor.tsx
  src/components/common/navBar/LocalNavBar.tsx
  src/components/login/LoginForm.tsx
  src/components/project/ProjectHeader.tsx
  src/components/thread/threadAiSummary/ThreadAiSummary.Style.ts
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.Style.ts
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketView/TicketListView.tsx
  src/pages/threadPage/ThreadPage.Style.ts
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.Style.ts
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  tsconfig.json
Labels: 🐞 bug, 🛠 refactor, 🐣 yumin

#81 feat, fix: 페이지 별 추가 UI 및 경로, 렌더링 처리
  src.zip
  src/api/Ticket.ts
  src/components/common/dropdown/BulkDropdown.tsx
  src/components/common/dropdown/Dropdown.style.ts
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/PortalDropdown.tsx
  src/components/common/modal/UserInfoLink.tsx
  src/components/common/modal/UserInfoModal.Style.ts
  src/components/common/modal/UserInfoModal.tsx
  src/components/common/navBar/WorkspaceSelector.Style.ts
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.tsx
  src/components/project/AddProjectMemberModal.tsx
  src/components/ticket/EmptyTicket.Style.ts
  src/components/ticket/EmptyTicket.tsx
  src/components/ticket/PriorityDropdown.Style.ts
  src/components/ticket/PriorityDropdown.tsx
  src/components/ticket/StatusDropdown.Style.ts
  src/components/ticket/StatusDropdown.tsx
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticket/TicketToolbar.tsx
  src/components/ticketView/TicketListView.tsx
  src/components/workspace/ImageUpload.tsx
  src/components/workspace/WorkspaceSelectorDropdown.Style.ts
  src/components/workspace/WorkspaceSelectorDropdown.tsx
  src/hooks/useOutsideClick.ts
  src/hooks/useUserInfoModal.ts
  src/hooks/useWorkspace.ts
  src/pages/memberPage/MemberPage.tsx
  src/pages/profilePage/profilePage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/pages/workspaceManagePage/WorkspaceInfoPage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
  src/stores/workspaceStore.ts
  src/utils/OutsideClick.ts
  src/utils/PortalDropdown.tsx
Labels: 🐞 bug, ⚙️ api, ✨ feature, 😺 wantyeon

#82 feat, fix: 페이지 별 추가 UI 및 경로, 렌더링 처리
  src.zip
  src/api/Ticket.ts
  src/components/common/dropdown/BulkDropdown.tsx
  src/components/common/dropdown/Dropdown.style.ts
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/PortalDropdown.tsx
  src/components/common/modal/UserInfoLink.tsx
  src/components/common/modal/UserInfoModal.Style.ts
  src/components/common/modal/UserInfoModal.tsx
  src/components/common/navBar/WorkspaceSelector.Style.ts
  src/components/common/navBar/WorkspaceSelector.tsx
  src/components/member/MemberRow.tsx
  src/components/member/MemberTable.tsx
  src/components/project/AddProjectMemberModal.tsx
  src/components/ticket/EmptyTicket.Style.ts
  src/components/ticket/EmptyTicket.tsx
  src/components/ticket/PriorityDropdown.Style.ts
  src/components/ticket/PriorityDropdown.tsx
  src/components/ticket/StatusDropdown.Style.ts
  src/components/ticket/StatusDropdown.tsx
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticket/TicketToolbar.tsx
  src/components/ticketView/TicketListView.tsx
  src/components/workspace/ImageUpload.tsx
  src/components/workspace/WorkspaceSelectorDropdown.Style.ts
  src/components/workspace/WorkspaceSelectorDropdown.tsx
  src/hooks/useOutsideClick.ts
  src/hooks/useUserInfoModal.ts
  src/hooks/useWorkspace.ts
  src/pages/memberPage/MemberPage.tsx
  src/pages/profilePage/profilePage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/pages/workspaceManagePage/WorkspaceInfoPage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
  src/stores/workspaceStore.ts
  src/utils/OutsideClick.ts
  src/utils/PortalDropdown.tsx
Labels: 🐞 bug, ⚙️ api, ✨ feature, 😺 wantyeon

#84 Feat/2 1 4/web socket
  public/images/.gitkeep
  public/images/avatar-1.png
  public/images/avatar-2.png
  public/images/avatar-3.png
  public/images/avatar-4.png
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/AvatarWithName.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/hooks/useWebSocket.ts
  src/pages/threadPage/ThreadPage.Style.ts
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/utils/formatDateTime.ts
Labels: ✨ feature, 🛠 refactor, 🐣 yumin

#85 WebSocket 연결 유지 및 티켓/프로젝트 리팩토링
  public/images/.gitkeep
  public/images/avatar-1.png
  public/images/avatar-2.png
  public/images/avatar-3.png
  public/images/avatar-4.png
  src/components/thread/threadChat/ThreadChat.Style.ts
  src/components/thread/threadChat/ThreadChat.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/AvatarWithName.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/hooks/useWebSocket.ts
  src/pages/threadPage/ThreadPage.Style.ts
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/utils/formatDateTime.ts
Labels: ✨ feature, 🛠 refactor, 🐣 yumin

#91 티켓 칸반보드 뷰 ui 구현 및 버그 픽스
  src/components/thread/threadAiSummary/ThreadAiSummary.Style.ts
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketView/TicketBoardView.Style.ts
  src/components/ticketView/TicketBoardView.tsx
  src/components/ticketView/TicketCard.Style.ts
  src/components/ticketView/TicketCard.tsx
  src/components/workspace/InviteModal.tsx
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/pages/workspacePage/WorkspacePage.tsx
  src/types/ticket.ts
  src/utils/ticketMapper.ts
Labels: 🐞 bug, ✨ feature, 🐣 yumin

#93 Ref/ut ym
  public/images/avatar-me.png
  src/Router.tsx
  src/components/thread/threadChat/ThreadChat.tsx
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticketView/TicketBoardView.Style.ts
  src/components/ticketView/TicketBoardView.tsx
  src/pages/threadPage/ThreadPage.tsx
  src/pages/threadPage/TreadPageWrapper.tsx
  src/utils/ticketMapper.ts
Labels: ✨ feature, 🐣 yumin

#97 ref: 워크스페이스 관련 페이지, 모달 모션 적용 및 렌더링 버그 처리
  src.zip
  src/components/common/dropdown/Dropdown.style.ts
  src/components/common/dropdown/Dropdown.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/pages/workspaceCreatePage/workspaceCreatePage.Style.ts
  src/pages/workspaceCreatePage/workspaceCreatePage.tsx
  src/pages/workspacePage/WorkspacePage.Style.ts
  src/pages/workspacePage/WorkspacePage.tsx
  src/utils/formatDateTime.ts
Labels: 🛠 refactor, 💄 ui, 😺 wantyeon

#100 feat: 서비스 main 페이지 구현 및 리액트 쿼리 설치
  eslint.config.js
  package-lock.json
  package.json
  public/images/dummy-1.png
  src/App.tsx
  src/AppInitializer.tsx
  src/Router.tsx
  src/components/common/navBar/GlobalNavBar.Style.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/pages/mainPage/MainPage.Style.ts
  src/pages/mainPage/MainPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 yumin

#101 feat: 서비스 main 페이지 구현 및 리액트 쿼리 설치
  eslint.config.js
  package-lock.json
  package.json
  public/images/dummy-1.png
  src/App.tsx
  src/AppInitializer.tsx
  src/Router.tsx
  src/components/common/navBar/GlobalNavBar.Style.ts
  src/components/common/navBar/GlobalNavBar.tsx
  src/pages/mainPage/MainPage.Style.ts
  src/pages/mainPage/MainPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 yumin

#106 feat: React Query 기반 티켓 단건 조회 및 ThreadInfo 수정 기능 적용
  src/components/login/OauthLoginButton.tsx
  src/components/login/SignUpForm.tsx
  src/components/thread/threadAiSummary/ThreadAiSummary.Style.ts
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticket/PriorityBadge.Style.ts
  src/components/ticket/StatusBadge.Style.ts
  src/components/ticket/StatusBadge.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.Style.ts
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketView/TicketBoardView.Style.ts
  src/pages/threadPage/ThreadPage.tsx
  src/types/ticket.ts
  vite.config.ts
Labels: 🐞 bug, ✨ feature, 🐣 yumin

#107 feat: 내 티켓, 하위티켓, 설정 경로 등 주요 UI/UX 기능 구현 및 개
  .gitignore
  package-lock.json
  package.json
  src.zip
  src/Router.tsx
  src/api/Workspace.ts
  src/components/common/navBar/LocalNavBar.Style.ts
  src/components/common/navBar/LocalNavBar.tsx
  src/components/common/navBar/ProjectNavBar.tsx
  src/components/common/navBar/SettingNavBar.tsx
  src/components/inviteCode/InviteEntry.tsx
  src/components/layout/WorkspaceLayout.tsx
  src/components/login/FindPasswordModal.Style.ts
  src/components/login/FindPasswordModal.tsx
  src/components/login/LoginForm.Style.ts
  src/components/login/LoginForm.tsx
  src/components/login/OauthLoginButton.tsx
  src/components/login/SignUpComplete.tsx
  src/components/login/SignUpForm.Style.ts
  src/components/login/SignUpForm.tsx
  src/components/ticket/AssignCell.Style.ts
  src/components/ticket/AssignCell.tsx
  src/components/ticket/AvatarWithName.tsx
  src/components/ticket/TicketRow.Style.ts
  src/components/ticket/TicketRow.tsx
  src/components/ticket/TicketTable.tsx
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/workspace/WorkspaceSelectorDropdown.tsx
  src/pages/InviteCodePage/InviteCodePage.tsx
  src/pages/findPasswordPage/FindPasswordPage.Style.ts
  src/pages/findPasswordPage/FindPasswordPage.tsx
  src/pages/loginPage/GoogleRedirect.tsx
  src/pages/myTicketPage/MyTicketPage.Style.ts
  src/pages/myTicketPage/MyTicketPage.tsx
  src/pages/projectPage/ProjectPage.tsx
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/pages/workspaceCreatePage/workspaceCreatePage.Style.ts
  src/pages/workspacePage/WorkspacePage.tsx
  src/utils/auth.ts
  src/utils/ticketMapper.ts
  vite.config.ts
Labels: ✨ feature, 🛠 refactor, 💄 ui, 😺 wantyeon

#110 feat: 티켓 템플릿 선택 및 스레드 Ai 요약 구현
  package-lock.json
  package.json
  src/api/Ai.ts
  src/api/Ticket.ts
  src/components/common/markdownEditor/MarkdownEditor.Style.ts
  src/components/common/markdownEditor/MarkdownEditor.tsx
  src/components/thread/threadAiSummary/ThreadAiSummary.tsx
  src/components/thread/threadInfo/ThreadInfo.Style.ts
  src/components/thread/threadInfo/ThreadInfo.tsx
  src/components/ticketDetailPanel/TicketDetailPanel.tsx
  src/components/ticketModal/CreateTicketModal.Style.ts
  src/components/ticketModal/CreateTicketModal.tsx
  src/components/ticketModal/TicketTemplateModal.Style.ts
  src/components/ticketModal/TicketTemplateModal.tsx
  src/constants/ticketTemplateData.ts
  src/pages/myTicketPage/MyTicketPage.tsx
  src/pages/threadPage/ThreadPage.tsx
  src/pages/ticketDashboardPage/TicketDashboardPage.tsx
  src/types/ticketTemplate.ts
  src/utils/ticketTemplateMapper.ts
  vite.config.ts
Labels: ⚙️ api, ✨ feature, 💄 ui, 🐣 yumin
